FROM debian

RUN apt-get update -y && apt-get upgrade -y &&  apt-get install curl -y
RUN apt-get install bzip2 -y

EXPOSE 9987/udp
EXPOSE 30033
EXPOSE 10011

RUN useradd ts3
WORKDIR teamspeak3
RUN curl http://dl.4players.de/ts/releases/3.0.13.6/teamspeak3-server_linux_amd64-3.0.13.6.tar.bz2 > teamspeak3-server.tar.bz2
RUN tar -xjvf teamspeak3-server.tar.bz2
WORKDIR teamspeak3-server_linux_amd64
COPY ts3server.ini /teamspeak3/teamspeak3-server_linux_amd64/ts3server.ini
USER ts3
ENTRYPOINT ["sh","ts3server_minimal_runscript.sh", "inifile=ts3server.ini"]
